[2025-07-14T02:34:05.274+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Run_data_quality_checks manual__2025-07-14T02:33:25.563358+00:00 [queued]>
[2025-07-14T02:34:05.283+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Run_data_quality_checks manual__2025-07-14T02:33:25.563358+00:00 [queued]>
[2025-07-14T02:34:05.283+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-07-14T02:34:05.299+0000] {taskinstance.py:1350} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2025-07-14 02:33:25.563358+00:00
[2025-07-14T02:34:05.306+0000] {standard_task_runner.py:57} INFO - Started process 772 to run task
[2025-07-14T02:34:05.311+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Run_data_quality_checks', 'manual__2025-07-14T02:33:25.563358+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpbu0zslr_']
[2025-07-14T02:34:05.313+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask Run_data_quality_checks
[2025-07-14T02:34:05.372+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Run_data_quality_checks manual__2025-07-14T02:33:25.563358+00:00 [running]> on host d7ac0fd04b06
[2025-07-14T02:34:05.500+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T02:33:25.563358+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-14T02:33:25.563358+00:00'
[2025-07-14T02:34:05.512+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:34:06.830+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM songplays, parameters: None
[2025-07-14T02:34:07.208+0000] {sql.py:384} INFO - Rows affected: 1
[2025-07-14T02:34:07.389+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/data_quality.py", line 36, in execute
    logging.info(f"Data quality on table {self.table} check passed with {records[0][0]} records")
AttributeError: 'DataQualityOperator' object has no attribute 'table'
[2025-07-14T02:34:07.405+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=final_project, task_id=Run_data_quality_checks, execution_date=20250714T023325, start_date=20250714T023405, end_date=20250714T023407
[2025-07-14T02:34:07.424+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 50 for task Run_data_quality_checks ('DataQualityOperator' object has no attribute 'table'; 772)
[2025-07-14T02:34:07.451+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-07-14T02:34:07.484+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
