[2025-07-14T02:26:18.948+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_user_dim_table manual__2025-07-14T02:25:31.239507+00:00 [queued]>
[2025-07-14T02:26:18.968+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_user_dim_table manual__2025-07-14T02:25:31.239507+00:00 [queued]>
[2025-07-14T02:26:18.969+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-07-14T02:26:18.989+0000] {taskinstance.py:1350} INFO - Executing <Task(LoadDimensionOperator): Load_user_dim_table> on 2025-07-14 02:25:31.239507+00:00
[2025-07-14T02:26:18.996+0000] {standard_task_runner.py:57} INFO - Started process 583 to run task
[2025-07-14T02:26:19.000+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_user_dim_table', 'manual__2025-07-14T02:25:31.239507+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpon0t47wr']
[2025-07-14T02:26:19.003+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask Load_user_dim_table
[2025-07-14T02:26:19.107+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Load_user_dim_table manual__2025-07-14T02:25:31.239507+00:00 [running]> on host d7ac0fd04b06
[2025-07-14T02:26:19.245+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T02:25:31.239507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-14T02:25:31.239507+00:00'
[2025-07-14T02:26:19.263+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:26:20.568+0000] {sql.py:375} INFO - Running statement: INSERT INTO user_table 
        SELECT distinct userid, firstname, lastname, gender, level
        FROM staging_events
        WHERE page='NextSong'
    ;, parameters: None
[2025-07-14T02:26:20.924+0000] {load_dimension.py:35} ERROR - 'user_table' へのデータのロード中にエラーが発生しました: relation "user_table" does not exist

[2025-07-14T02:26:20.925+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/load_dimension.py", line 33, in execute
    redshift.run(exec_sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "user_table" does not exist

[2025-07-14T02:26:20.941+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=final_project, task_id=Load_user_dim_table, execution_date=20250714T022531, start_date=20250714T022618, end_date=20250714T022620
[2025-07-14T02:26:20.963+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 29 for task Load_user_dim_table (relation "user_table" does not exist
; 583)
[2025-07-14T02:26:21.008+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-07-14T02:26:21.056+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
